// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../../src/application/features/repositories/register_processor.go
//
// Generated by this command:
//
//	mockgen -source=../../../../src/application/features/repositories/register_processor.go -destination=mock/register_processor.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRegisterProcessorRepository is a mock of RegisterProcessorRepository interface.
type MockRegisterProcessorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterProcessorRepositoryMockRecorder
}

// MockRegisterProcessorRepositoryMockRecorder is the mock recorder for MockRegisterProcessorRepository.
type MockRegisterProcessorRepositoryMockRecorder struct {
	mock *MockRegisterProcessorRepository
}

// NewMockRegisterProcessorRepository creates a new mock instance.
func NewMockRegisterProcessorRepository(ctrl *gomock.Controller) *MockRegisterProcessorRepository {
	mock := &MockRegisterProcessorRepository{ctrl: ctrl}
	mock.recorder = &MockRegisterProcessorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegisterProcessorRepository) EXPECT() *MockRegisterProcessorRepositoryMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRegisterProcessorRepository) Execute(query string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", query)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockRegisterProcessorRepositoryMockRecorder) Execute(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRegisterProcessorRepository)(nil).Execute), query)
}
