// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"Felyp-Henrique/syncd/src/infrastructure/server"
)

// Injectors from wire.go:

func InjectHttpServer() *server.HttpServer {
	httpServer := server.NewHttpServer()
	return httpServer
}
